-- ============================================================
-- CASA OITO DEL MARE · PÁGINA DE LINKS + PONTOS TURÍSTICOS
-- Execute uma vez no SQL Editor do Supabase.
-- ============================================================

create extension if not exists "pgcrypto";

-- ------------------------------------------------------------
-- PÁGINA DE LINKS
-- ------------------------------------------------------------
create table if not exists public.link_page_settings (
  id integer primary key default 1 check (id = 1),
  profile jsonb not null default '{}'::jsonb,
  appearance jsonb not null default '{}'::jsonb,
  links jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.link_page_settings enable row level security;

drop policy if exists "public can read link page" on public.link_page_settings;
create policy "public can read link page"
on public.link_page_settings for select to anon, authenticated using (true);

drop policy if exists "authenticated can manage link page" on public.link_page_settings;
create policy "authenticated can manage link page"
on public.link_page_settings for all to authenticated using (true) with check (true);

-- Mantém os dados já existentes. Só adiciona os novos cards quando ainda não existirem.
do $$
declare
  current_profile jsonb;
  current_links jsonb;
begin
  select profile, links into current_profile, current_links
  from public.link_page_settings where id = 1;

  if not found then
    insert into public.link_page_settings (id, profile, appearance, links)
    values (
      1,
      '{"name":"Casa Oito Del Mare","location":"ARMAÇÃO DOS BÚZIOS · RJ","bio":"Onde o tempo desacelera e Búzios começa.","instagram":"https://www.instagram.com/casaoitodelmare/","whatsapp":"5521986362770","map":"https://www.google.com/maps/search/?api=1&query=Arma%C3%A7%C3%A3o+dos+B%C3%BAzios+RJ","contact":{"phones":["(21) 98636-2770","(21) 98635-7913"],"instagram":"https://www.instagram.com/casaoitodelmare/"}}'::jsonb,
      '{"quote":"Dias de sol. Noites tranquilas.|Memórias para levar.","featuredFirst":true}'::jsonb,
      '[
        {"title":"Consulte sua estadia","subtitle":"Disponibilidade e informações","url":"https://wa.me/5521986362770","icon":"📅","featured":true,"active":true,"type":"whatsapp","image_url":""},
        {"title":"Pontos turísticos de Búzios","subtitle":"Praias, mirantes e lugares para descobrir","url":"#tourism","icon":"◌","featured":true,"active":true,"type":"tourism","image_url":""},
        {"title":"Conheça a casa","subtitle":"Ambientes, detalhes e experiências","url":"../#cards","icon":"8","active":true,"type":"link","image_url":""},
        {"title":"Instagram","subtitle":"Acompanhe a Casa Oito Del Mare","url":"https://www.instagram.com/casaoitodelmare/","icon":"◎","active":true,"type":"link","image_url":""},
        {"title":"Onde estamos","subtitle":"Veja a localização em Búzios","url":"__MAP__","icon":"⌖","active":true,"type":"map","image_url":""},
        {"title":"Contato","subtitle":"Telefones e Instagram","url":"#contact","icon":"◍","active":true,"type":"contact","image_url":""}
      ]'::jsonb
    );
  else
    current_profile := coalesce(current_profile, '{}'::jsonb);
    current_links := coalesce(current_links, '[]'::jsonb);

    if not (current_profile ? 'contact') then
      current_profile := jsonb_set(
        current_profile,
        '{contact}',
        '{"phones":["(21) 98636-2770","(21) 98635-7913"],"instagram":"https://www.instagram.com/casaoitodelmare/"}'::jsonb,
        true
      );
    end if;

    if not exists (select 1 from jsonb_array_elements(current_links) x where x->>'type' = 'tourism') then
      current_links := current_links || '[{"title":"Pontos turísticos de Búzios","subtitle":"Praias, mirantes e lugares para descobrir","url":"#tourism","icon":"◌","featured":true,"active":true,"type":"tourism","image_url":""}]'::jsonb;
    end if;

    if not exists (select 1 from jsonb_array_elements(current_links) x where x->>'type' = 'contact') then
      current_links := current_links || '[{"title":"Contato","subtitle":"Telefones e Instagram","url":"#contact","icon":"◍","active":true,"type":"contact","image_url":""}]'::jsonb;
    end if;

    update public.link_page_settings
    set profile = current_profile, links = current_links, updated_at = now()
    where id = 1;
  end if;
end $$;

-- ------------------------------------------------------------
-- TEXTOS EDITÁVEIS DO SITE (garantia para o Admin)
-- ------------------------------------------------------------
create table if not exists public.site_content (
  id bigint generated by default as identity primary key,
  key text not null unique,
  title text not null,
  value text not null default '',
  section text not null default 'Geral',
  active boolean not null default true,
  updated_at timestamptz not null default now()
);

alter table public.site_content enable row level security;

drop policy if exists "Public can read active site content" on public.site_content;
create policy "Public can read active site content" on public.site_content
  for select to anon, authenticated using (active = true);

drop policy if exists "Authenticated can manage site content" on public.site_content;
create policy "Authenticated can manage site content" on public.site_content
  for all to authenticated using (true) with check (true);

insert into public.site_content (key,title,value,section,active) values
 ('hero_tagline','Frase de abertura','O mar logo ali. O tempo, todo seu.','Início',true),
 ('intro_eyebrow','Chamada da apresentação','UM REFÚGIO DE FAMÍLIA','Início',true),
 ('intro_body','Texto de apresentação','Há mais de quinze anos, a Casa Oito é o refúgio de uma família. Um lugar de silêncio, mar calmo e dias inteiros sem pressa — para chegar, respirar fundo e se sentir em casa.','Início',true),
 ('intro_link','Link da apresentação','Conheça cada cantinho','Início',true),
 ('quote_text','Frase de destaque','“É praticamente obrigatório caminhar nessa praia de manhã.”','Início',true),
 ('footer_eyebrow','Chamada do rodapé','O MAR JÁ ESTÁ ESPERANDO','Rodapé',true),
 ('footer_title','Título do rodapé','Seu próximo dia leve.','Rodapé',true),
 ('drawer_casa_title','Título · A casa','Por dentro da Casa Oito.','A casa',true),
 ('drawer_casa_body','Apresentação · A casa','Os espaços da casa, os detalhes de família e a paisagem que dá vontade de ficar mais um pouco.','A casa',true),
 ('drawer_structure_title','Título · Estrutura','Conforto de casa, pé na areia.','A experiência',true),
 ('drawer_structure_body','Apresentação · Estrutura','A Casa Oito recebe famílias com comodidade e simplicidade. A praia em frente e as áreas do condomínio completam os dias de descanso.','A experiência',true),
 ('drawer_structure_note','Frase · Estrutura','Quinze anos de histórias de família, cuidados e manhãs que começam com o som do mar.','A experiência',true),
 ('drawer_buzios_title','Título · Búzios','Búzios em movimento.','Búzios',true),
 ('drawer_buzios_body','Apresentação · Búzios','Armação dos Búzios, Rio de Janeiro. A Casa Oito fica à beira-mar, num condomínio familiar e tranquilo.','Búzios',true),
 ('drawer_reserve_title','Título · Reservas','Venha viver essa experiência.','Reservas',true),
 ('drawer_reserve_body','Apresentação · Reservas','Consulte datas, tire dúvidas e combine sua estadia diretamente com as proprietárias.','Reservas',true),
 ('drawer_privacy','Informação de privacidade','O condomínio é familiar e tranquilo. Para preservar a privacidade, o endereço completo é informado no momento da reserva. Check-in e check-out são combinados com as proprietárias.','Reservas',true)
on conflict (key) do nothing;

-- ------------------------------------------------------------
-- PONTOS TURÍSTICOS
-- ------------------------------------------------------------
create table if not exists public.tourist_points (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  subtitle text,
  description text,
  category text not null default 'Praia',
  recommendation text,
  image_url text,
  map_url text,
  instagram_url text,
  tripadvisor_url text,
  position integer not null default 0,
  active boolean not null default true,
  featured boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.tourist_points add column if not exists tripadvisor_url text;

alter table public.tourist_points enable row level security;

drop policy if exists "public can read active tourist points" on public.tourist_points;
create policy "public can read active tourist points"
on public.tourist_points for select to anon, authenticated using (active = true);

drop policy if exists "authenticated can manage tourist points" on public.tourist_points;
create policy "authenticated can manage tourist points"
on public.tourist_points for all to authenticated using (true) with check (true);

insert into public.tourist_points
  (title, subtitle, description, category, recommendation, image_url, map_url, position, active, featured)
select * from (values
  ('Orla Bardot', 'Caminhada · pôr do sol', 'Calçadão à beira-mar com barcos, esculturas e a atmosfera que virou uma das imagens mais conhecidas de Búzios.', 'Passeio', 'Vá no fim da tarde e siga caminhando até a Rua das Pedras.', 'https://www.civitatis.com/blog/wp-content/uploads/2025/09/shutterstock_251424757-1280x854.jpg', 'https://www.google.com/maps/search/?api=1&query=Orla+Bardot+B%C3%BAzios', 10, true, true),
  ('Rua das Pedras', 'Centro · gastronomia', 'O coração noturno de Búzios reúne restaurantes, bares, cafés, lojas e galerias em uma caminhada cheia de charme.', 'Centro', 'Chegue no fim da tarde para aproveitar o movimento com mais calma.', 'https://lirp.cdn-website.com/cb037d13/dms3rep/multi/opt/anexogeriba111-640w.jpg', 'https://www.google.com/maps/search/?api=1&query=Rua+das+Pedras+B%C3%BAzios', 20, true, true),
  ('Praia de João Fernandes', 'Mar calmo · snorkel', 'Uma das praias mais conhecidas da península, com águas claras e estrutura para passar algumas horas perto do mar.', 'Praia', 'Para um dia tranquilo, chegue cedo e leve máscara para snorkel.', 'https://i0.statig.com.br/bancodeimagens/b4/6s/zy/b46szy4zljpkh2giovee4c2dc.jpg', 'https://www.google.com/maps/search/?api=1&query=Praia+de+Jo%C3%A3o+Fernandes+B%C3%BAzios', 30, true, true),
  ('Praia da Azeda e Azedinha', 'Enseadas · águas claras', 'Duas pequenas praias cercadas por vegetação e costões, acessíveis a partir da região da Praia dos Ossos.', 'Praia', 'Reserve algumas horas e combine com uma caminhada pela Praia dos Ossos.', 'https://arrumaessamala.com.br/wp-content/uploads/2020/01/praia-da-azeda-buzios.jpg', 'https://www.google.com/maps/search/?api=1&query=Praia+da+Azeda+B%C3%BAzios', 40, true, true),
  ('Praia de Geribá', 'Surf · faixa de areia', 'Uma das praias mais movimentadas de Búzios, com mar aberto, faixa de areia ampla e clima esportivo.', 'Praia', 'Boa escolha para quem gosta de ondas e quer um dia de praia mais animado.', 'https://cdn.shopify.com/s/files/1/0048/7181/5256/files/Geriba.jpg?v=1696016186', 'https://www.google.com/maps/search/?api=1&query=Praia+de+Gerib%C3%A1+B%C3%BAzios', 50, true, false),
  ('Praia da Ferradura', 'Enseada · mar protegido', 'A enseada em formato de ferradura tem águas mais protegidas e um visual amplo, ótima para um dia de descanso.', 'Praia', 'Combine com uma manhã tranquila de mar e almoço sem pressa.', './assets/gallery/casa-14.jpg', 'https://www.google.com/maps/search/?api=1&query=Praia+da+Ferradura+B%C3%BAzios', 60, true, false),
  ('Praia dos Ossos', 'História · caminhada', 'Uma das praias mais tradicionais da península, próxima da Igreja de Sant’Ana e caminho para Azeda e Azedinha.', 'História', 'Use como ponto de partida para conhecer a região caminhando.', './assets/gallery/detalhe-12.jpg', 'https://www.google.com/maps/search/?api=1&query=Praia+dos+Ossos+B%C3%BAzios', 70, true, false),
  ('Porto da Barra', 'Gastronomia · pôr do sol', 'Complexo à beira da Praia de Manguinhos com restaurantes, lojas e um clima especial no fim do dia.', 'Gastronomia', 'Ótimo para terminar o dia com jantar e pôr do sol.', './assets/gallery/detalhe-09.jpg', 'https://www.google.com/maps/search/?api=1&query=Porto+da+Barra+B%C3%BAzios', 80, true, false)
) as seed(title, subtitle, description, category, recommendation, image_url, map_url, position, active, featured)
where not exists (select 1 from public.tourist_points);

update public.tourist_points
set tripadvisor_url = 'https://www.tripadvisor.com.br/Search?q=' || replace(title || ' Búzios', ' ', '+')
where tripadvisor_url is null or tripadvisor_url = '';

-- Posições consecutivas.
with ordered as (
  select id, row_number() over (order by position, id) as new_position
  from public.tourist_points
)
update public.tourist_points p
set position = o.new_position
from ordered o
where p.id = o.id and p.position is distinct from o.new_position;

-- Garante que o card de turismo já existente também tenha uma imagem de capa.
update public.link_page_settings
set links = (
  select jsonb_agg(
    case
      when x->>'type' = 'tourism' and coalesce(x->>'image_url','') = ''
        then jsonb_set(x, '{image_url}', to_jsonb('./assets/gallery/detalhe-11.jpg'::text), true)
      else x
    end
    order by ord
  )
  from jsonb_array_elements(coalesce(links,'[]'::jsonb)) with ordinality as t(x,ord)
), updated_at = now()
where id = 1;

notify pgrst, 'reload schema';

-- ------------------------------------------------------------
-- CONFIGURAÇÃO DO CALENDÁRIO DE ESTADIA
-- ------------------------------------------------------------
alter table public.link_page_settings
  add column if not exists availability jsonb not null default '{"enabled":true,"title":"Consulte sua estadia.","subtitle":"As datas em vermelho já estão reservadas. As demais estão livres para consulta.","reservedDates":[],"whatsapp":"5521986362770"}'::jsonb;

update public.link_page_settings
set availability = coalesce(availability, '{}'::jsonb) || jsonb_build_object(
  'enabled', coalesce((availability->>'enabled')::boolean, true),
  'title', coalesce(availability->>'title', 'Consulte sua estadia.'),
  'subtitle', coalesce(availability->>'subtitle', 'As datas em vermelho já estão reservadas. As demais estão livres para consulta.'),
  'reservedDates', coalesce(availability->'reservedDates', '[]'::jsonb),
  'whatsapp', coalesce(availability->>'whatsapp', profile->>'whatsapp', '5521986362770')
)
where id = 1;

notify pgrst, 'reload schema';
